### ISSUE TITLE
after open video , nothing happened

### ISSUE THREAD

**Issue by debobh** [leejh3224/youtube-bot#3]
leejh , I executed in git bash but aonly one task completed is video is open in youtube ,what can i do for execute complete program

**Comment by edcarSky** [comment]
i have issue on this part even i have chromedriver

C:\Python36\youtube-bot-master>main.py
Traceback (most recent call last):
  File "C:\Python36\youtube-bot-master\main.py", line 1, in <module>
    from Bot import Bot
  File "C:\Python36\youtube-bot-master\Bot.py", line 1, in <module>
    from selenium import webdriver
ImportError: No module named selenium

**Comment by Plutonlum** [comment]
Dont execute it its most likely a logger or phishing
